<?php

namespace ContainerB63shrs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivrablePartielControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\LivrablePartielController' shared autowired service.
     *
     * @return \App\Controller\LivrablePartielController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/LivrablePartielController.php';

        $container->services['App\\Controller\\LivrablePartielController'] = $instance = new \App\Controller\LivrablePartielController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\LivrablePartielController', $container));

        return $instance;
    }
}
