<?php

namespace ContainerXYOLo0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1h0fIZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1h0fI_z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1h0fI_z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repoRendu' => ['privates', 'App\\Repository\\LivrableRenduRepository', 'getLivrableRenduRepositoryService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
        ], [
            'manager' => '?',
            'repoRendu' => 'App\\Repository\\LivrableRenduRepository',
            'serializer' => '?',
        ]);
    }
}
