<?php

namespace ContainerXYOLo0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FqPzyjvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fqPzyjv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fqPzyjv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repoPromo' => ['privates', 'App\\Repository\\PromoRepository', 'getPromoRepositoryService', true],
            'repoRef' => ['privates', 'App\\Repository\\ReferentielRepository', 'getReferentielRepositoryService', true],
            'repoSt' => ['privates', 'App\\Repository\\StatistiquesCompetencesRepository', 'getStatistiquesCompetencesRepositoryService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
        ], [
            'repoPromo' => 'App\\Repository\\PromoRepository',
            'repoRef' => 'App\\Repository\\ReferentielRepository',
            'repoSt' => 'App\\Repository\\StatistiquesCompetencesRepository',
            'serializer' => '?',
        ]);
    }
}
