<?php

namespace ContainerIYXdo2B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P8Oaf2AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P8Oaf2A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P8Oaf2A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::getAdmin' => ['privates', '.service_locator.RTUGCCW', 'get_ServiceLocator_RTUGCCWService', true],
            'App\\Controller\\AdminController::getAdminById' => ['privates', '.service_locator.olU6qez', 'get_ServiceLocator_OlU6qezService', true],
            'App\\Controller\\ApprenantController::getApprenant' => ['privates', '.service_locator.RTUGCCW', 'get_ServiceLocator_RTUGCCWService', true],
            'App\\Controller\\ApprenantController::getApprenantById' => ['privates', '.service_locator.olU6qez', 'get_ServiceLocator_OlU6qezService', true],
            'App\\Controller\\FormateurController::getFormateur' => ['privates', '.service_locator.RTUGCCW', 'get_ServiceLocator_RTUGCCWService', true],
            'App\\Controller\\FormateurController::getFormateurById' => ['privates', '.service_locator.olU6qez', 'get_ServiceLocator_OlU6qezService', true],
            'App\\Controller\\UserController::addUser' => ['privates', '.service_locator.r5pch1I', 'get_ServiceLocator_R5pch1IService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\AdminController:getAdmin' => ['privates', '.service_locator.RTUGCCW', 'get_ServiceLocator_RTUGCCWService', true],
            'App\\Controller\\AdminController:getAdminById' => ['privates', '.service_locator.olU6qez', 'get_ServiceLocator_OlU6qezService', true],
            'App\\Controller\\ApprenantController:getApprenant' => ['privates', '.service_locator.RTUGCCW', 'get_ServiceLocator_RTUGCCWService', true],
            'App\\Controller\\ApprenantController:getApprenantById' => ['privates', '.service_locator.olU6qez', 'get_ServiceLocator_OlU6qezService', true],
            'App\\Controller\\FormateurController:getFormateur' => ['privates', '.service_locator.RTUGCCW', 'get_ServiceLocator_RTUGCCWService', true],
            'App\\Controller\\FormateurController:getFormateurById' => ['privates', '.service_locator.olU6qez', 'get_ServiceLocator_OlU6qezService', true],
            'App\\Controller\\UserController:addUser' => ['privates', '.service_locator.r5pch1I', 'get_ServiceLocator_R5pch1IService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\AdminController::getAdmin' => '?',
            'App\\Controller\\AdminController::getAdminById' => '?',
            'App\\Controller\\ApprenantController::getApprenant' => '?',
            'App\\Controller\\ApprenantController::getApprenantById' => '?',
            'App\\Controller\\FormateurController::getFormateur' => '?',
            'App\\Controller\\FormateurController::getFormateurById' => '?',
            'App\\Controller\\UserController::addUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:getAdmin' => '?',
            'App\\Controller\\AdminController:getAdminById' => '?',
            'App\\Controller\\ApprenantController:getApprenant' => '?',
            'App\\Controller\\ApprenantController:getApprenantById' => '?',
            'App\\Controller\\FormateurController:getFormateur' => '?',
            'App\\Controller\\FormateurController:getFormateurById' => '?',
            'App\\Controller\\UserController:addUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
