<?php

namespace Container0HnDZ0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TYfDJRlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tYfDJRl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tYfDJRl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'rep_cmp' => ['privates', 'App\\Repository\\CompetenceRepository', 'getCompetenceRepositoryService', true],
            'rep_niveau' => ['privates', '.errored.RUAiUhv', NULL, 'Cannot determine controller argument for "App\\Controller\\CompetenceController::updateCompetence()": the $rep_niveau argument is type-hinted with the non-existent class or interface: "App\\Controller\\NiveauRepository". Did you forget to add a use statement?'],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
            'validator' => ['services', 'validator', 'getValidatorService', false],
        ], [
            'manager' => '?',
            'rep_cmp' => 'App\\Repository\\CompetenceRepository',
            'rep_niveau' => '?',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
