<?php

namespace Container0HnDZ0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_RUAiUhvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.RUAiUhv' shared service.
     *
     * @return \App\Controller\NiveauRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\CompetenceController::updateCompetence()": the $rep_niveau argument is type-hinted with the non-existent class or interface: "App\\Controller\\NiveauRepository". Did you forget to add a use statement?');
    }
}
