<?php

namespace ContainerFbR0NZR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DscxL_4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DscxL.4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DscxL.4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'brief' => ['privates', 'App\\Repository\\BriefRepository', 'getBriefRepositoryService', true],
        ], [
            'brief' => 'App\\Repository\\BriefRepository',
        ]);
    }
}
