<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO1W64L3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO1W64L3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO1W64L3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO1W64L3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO1W64L3\App_KernelDevDebugContainer([
    'container.build_hash' => 'O1W64L3',
    'container.build_id' => 'a5dd5629',
    'container.build_time' => 1597322438,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO1W64L3');
