<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXVfKXKc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXVfKXKc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXVfKXKc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXVfKXKc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXVfKXKc\App_KernelDevDebugContainer([
    'container.build_hash' => 'XVfKXKc',
    'container.build_id' => 'd732de25',
    'container.build_time' => 1598353467,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXVfKXKc');
