<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerURSqSl3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerURSqSl3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerURSqSl3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerURSqSl3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerURSqSl3\App_KernelDevDebugContainer([
    'container.build_hash' => 'URSqSl3',
    'container.build_id' => '508d9485',
    'container.build_time' => 1596859245,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerURSqSl3');
